# camryn echevarria
# 11/28/2022

# problem 3 write a list of numbers and multiply them.

import random

# create a list were we will store the numbers generated by a for loop
Number_List = []

# for loop that generates 10 random numbers
for num in range(1, 11):

    Number_List.append(random.randint(1, 101))
# show the user the 10 random numbers generated
print(Number_List)
def multiplylist(list_of_numbers):
    # multiply the first number by 1 so we get itself
    answer: int = 1
    for number in list_of_numbers:

     return answer
